"""
Create Professional Project Poster with Actual Visualizations
Uses the real charts generated by the project
"""

from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from PIL import Image
import os

def create_poster_with_visuals():
    """Create poster embedding actual project visualizations"""
    
    filename = "PROJECT_POSTER.pdf"
    c = canvas.Canvas(filename, pagesize=landscape(A4))
    width, height = landscape(A4)
    
    # Colors
    header_blue = colors.HexColor('#1e3a8a')
    accent_green = colors.HexColor('#059669')
    light_gray = colors.HexColor('#f3f4f6')
    dark_gray = colors.HexColor('#374151')
    
    # ========================================================================
    # HEADER
    # ========================================================================
    c.setFillColor(header_blue)
    c.rect(0, height - 1.2*inch, width, 1.2*inch, fill=True, stroke=False)
    
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 32)
    c.drawCentredString(width/2, height - 0.6*inch, "HR RECRUITMENT FUNNEL ANALYTICS")
    
    c.setFont("Helvetica", 14)
    c.drawCentredString(width/2, height - 0.95*inch, "Enterprise-Grade ML-Powered Recruitment Intelligence Platform")
    
    # ========================================================================
    # LEFT COLUMN - Problem & Achievements
    # ========================================================================
    x_left = 0.5*inch
    y = height - 1.5*inch
    
    # Problem Statement
    c.setFillColor(dark_gray)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(x_left, y, "📊 Problem Statement")
    y -= 0.25*inch
    
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.black)
    problem_text = [
        "• 1,480 applicants across 8 hiring stages",
        "• Manual tracking prevents insights",
        "• Need data-driven optimization"
    ]
    for line in problem_text:
        c.drawString(x_left, y, line)
        y -= 0.2*inch
    
    y -= 0.2*inch
    
    # Key Achievements
    c.setFillColor(accent_green)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(x_left, y, "✅ Key Achievements")
    y -= 0.25*inch
    
    achievements = [
        "✓ 45.4% drop-off identified",
        "✓ 97.8% ML accuracy (ROC-AUC)",
        "✓ Company Website 27% better",
        "✓ 43-day avg time-to-hire"
    ]
    
    c.setFont("Helvetica-Bold", 10)
    c.setFillColor(colors.black)
    for achievement in achievements:
        c.drawString(x_left, y, achievement)
        y -= 0.2*inch
    
    y -= 0.2*inch
    
    # Tech Stack
    c.setFillColor(header_blue)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(x_left, y, "🛠 Tech Stack")
    y -= 0.25*inch
    
    tech_stack = [
        "Python • SQL • Machine Learning",
        "Random Forest • Gradient Boosting",
        "Streamlit • FastAPI • Plotly"
    ]
    
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.black)
    for tech in tech_stack:
        c.drawString(x_left, y, tech)
        y -= 0.18*inch
    
    # ========================================================================
    # CENTER - VISUALIZATIONS
    # ========================================================================
    x_center = 3*inch
    y_viz = height - 1.5*inch
    
    # Title
    c.setFillColor(dark_gray)
    c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(x_center + 2*inch, y_viz, "📈 Data Visualizations")
    y_viz -= 0.3*inch
    
    # Embed actual visualizations
    viz_width = 4*inch
    viz_height = 1.8*inch
    
    # Recruitment Funnel
    if os.path.exists('visualizations/recruitment_funnel.png'):
        c.drawImage('visualizations/recruitment_funnel.png', 
                    x_center, y_viz - viz_height, 
                    width=viz_width, height=viz_height, 
                    preserveAspectRatio=True, mask='auto')
        c.setFont("Helvetica", 8)
        c.setFillColor(dark_gray)
        c.drawCentredString(x_center + viz_width/2, y_viz - viz_height - 0.15*inch, 
                          "Recruitment Funnel - Stage Progression")
    
    y_viz -= viz_height + 0.4*inch
    
    # Drop-off Analysis
    if os.path.exists('visualizations/drop_off_analysis.png'):
        c.drawImage('visualizations/drop_off_analysis.png', 
                    x_center, y_viz - viz_height, 
                    width=viz_width, height=viz_height, 
                    preserveAspectRatio=True, mask='auto')
        c.setFont("Helvetica", 8)
        c.setFillColor(dark_gray)
        c.drawCentredString(x_center + viz_width/2, y_viz - viz_height - 0.15*inch, 
                          "Drop-off Analysis - Technical Round Bottleneck (45.4%)")
    
    # ========================================================================
    # RIGHT COLUMN - ML Performance & Business Impact
    # ========================================================================
    x_right = width - 2.8*inch
    y_right = height - 1.5*inch
    
    # ML Model Performance
    c.setFillColor(accent_green)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(x_right, y_right, "🤖 ML Performance")
    y_right -= 0.25*inch
    
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(colors.black)
    c.drawString(x_right, y_right, "ROC-AUC: 97.8%")
    y_right -= 0.2*inch
    c.setFont("Helvetica", 9)
    c.drawString(x_right, y_right, "Accuracy: 92.0%")
    y_right -= 0.18*inch
    c.drawString(x_right, y_right, "F1-Score: 81.9%")
    y_right -= 0.3*inch
    
    # Feature Importance visualization (small)
    if os.path.exists('visualizations/feature_importance.png'):
        img_width = 2.5*inch
        img_height = 1.5*inch
        c.drawImage('visualizations/feature_importance.png', 
                    x_right, y_right - img_height, 
                    width=img_width, height=img_height, 
                    preserveAspectRatio=True, mask='auto')
        y_right -= img_height + 0.3*inch
    
    # Business Impact
    c.setFillColor(header_blue)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(x_right, y_right, "💼 Business Impact")
    y_right -= 0.25*inch
    
    c.setFont("Helvetica-Bold", 10)
    c.setFillColor(dark_gray)
    c.drawString(x_right, y_right, "Source Effectiveness:")
    y_right -= 0.2*inch
    
    sources = [
        ("Company Website", "19.4%"),
        ("Campus Hiring", "16.4%"),
        ("LinkedIn", "15.9%"),
        ("Naukri", "15.2%")
    ]
    
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.black)
    for source, rate in sources:
        c.drawString(x_right, y_right, f"• {source}: {rate}")
        y_right -= 0.18*inch
    
    y_right -= 0.2*inch
    
    # Recommendations
    c.setFillColor(colors.HexColor('#f59e0b'))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_right, y_right, "💡 Recommendations")
    y_right -= 0.22*inch
    
    recommendations = [
        "1. Fix Technical bottleneck",
        "2. Budget reallocation (+35%)",
        "3. ML-driven interventions"
    ]
    
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.black)
    for rec in recommendations:
        c.drawString(x_right, y_right, rec)
        y_right -= 0.18*inch
    
    # ========================================================================
    # FOOTER
    # ========================================================================
    c.setFillColor(light_gray)
    c.rect(0, 0, width, 0.6*inch, fill=True, stroke=False)
    
    c.setFillColor(header_blue)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.5*inch, 0.3*inch, "👤 Divya Dhole")
    
    c.setFont("Helvetica-Bold", 11)
    c.drawString(width/2 - 2*inch, 0.3*inch, 
                 "🔗 github.com/Divyadhole/HR-Recruitment-Funnel")
    
    # Save
    c.save()
    print(f"✅ Poster saved: {filename}")
    print(f"   Embedded visualizations:")
    print(f"      - recruitment_funnel.png")
    print(f"      - drop_off_analysis.png")
    print(f"      - feature_importance.png")

if __name__ == "__main__":
    print("=" * 70)
    print("CREATING PROJECT POSTER WITH VISUALIZATIONS")
    print("=" * 70)
    create_poster_with_visuals()
    print("=" * 70)
